#!/usr/bin/env python3
"""Integrity checks for the atlas data.

Run from the repository root:

    python3 scripts/check_data.py

Covers both data files. `maps.json` drives the static gallery and the 211 map
pages; `interactive-data.json` drives the choropleth on `explore.html`. Until
2026-09-22 the second one was checked by nothing at all, and the workflow that
checked the first only ran when `data/maps.json` or `maps/**` changed, so an
edit to the interactive layer alone triggered no job.

Every failure guarded here is quiet. Nothing in this repository throws.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Keys every indicator must carry. `higherIsBetter` and `national` are in the
# core set on purpose: both are optional as far as the renderer is concerned,
# and both change what the map means rather than whether it draws.
CORE_KEYS = {
    'id', 'theme', 'name', 'unit', 'source', 'year', 'desc',
    'higherIsBetter', 'national', 'sourceUrl', 'values',
    'name_hi', 'desc_hi', 'unit_hi',
}
OPTIONAL_KEYS = {'mapId', 'retrieved'}

errors = []
checks = 0


def check(name, ok, detail=''):
    global checks
    checks += 1
    if not ok:
        errors.append('%s: %s' % (name, detail))


def load(path):
    with open(os.path.join(ROOT, path), encoding='utf-8') as fh:
        return json.load(fh)


def main():
    geo = load('data/india-states.geojson')
    states = {f['properties']['name'] for f in geo['features']}
    check('geojson carries 36 states and UTs', len(states) == 36, '%d found' % len(states))

    maps = load('data/maps.json')
    data = load('data/interactive-data.json')

    # ---------------------------------------------------------------- maps.json
    ids = [m.get('id') for m in maps]
    check('maps.json ids are unique', len(ids) == len(set(ids)),
          'duplicates: %s' % sorted({i for i in ids if ids.count(i) > 1}))

    for field in ('id', 'title', 'section', 'source'):
        missing = [m.get('id', '?') for m in maps if not m.get(field)]
        check('maps.json entries all carry %s' % field, not missing,
              '%d without: %s' % (len(missing), missing[:6]))

    absent = [
        'maps/%s/%s' % (m['section'], m['file'])
        for m in maps if m.get('file')
        and not os.path.exists(os.path.join(ROOT, 'maps', m['section'], m['file']))
    ]
    check('every map image is on disk', not absent,
          '%d missing: %s' % (len(absent), absent[:5]))

    # The pages under m/ are generated by scripts/build_map_pages.py. Adding a
    # map without re-running it leaves an entry the gallery links to and no page
    # behind it, which is a 404 rather than an error anyone sees in a build.
    pageless = [m['id'] for m in maps if m.get('file')
                and not os.path.exists(os.path.join(ROOT, 'm', '%s.html' % m['id']))]
    check('every map has its generated page', not pageless,
          '%d without a page in m/: %s' % (len(pageless), pageless[:6]))

    on_disk = {f[:-5] for f in os.listdir(os.path.join(ROOT, 'm')) if f.endswith('.html')}
    orphans = sorted(on_disk - set(ids) - {'index'})
    check('no page in m/ outlives its map entry', not orphans,
          '%d orphaned: %s' % (len(orphans), orphans[:6]))

    sitemap = open(os.path.join(ROOT, 'sitemap.xml'), encoding='utf-8').read()
    unlisted = [m['id'] for m in maps if m.get('file')
                and '/m/%s.html' % m['id'] not in sitemap]
    check('sitemap.xml lists every map page', not unlisted,
          '%d absent, sitemap is stale: %s' % (len(unlisted), unlisted[:6]))

    # Three files state the map count in prose. A count that is written down
    # rather than derived goes stale the first time a map is added.
    n_maps = len(maps)
    for path in ('scripts/build_map_pages.py', 'data/README.md', 'README.md'):
        text = open(os.path.join(ROOT, path), encoding='utf-8').read()
        stale = sorted({int(n) for n in re.findall(r'\b(\d{3})\s+(?:static\s+)?maps\b', text)
                        if int(n) != n_maps})
        check('%s states the map count as %d' % (path, n_maps), not stale,
              'says %s' % stale)

    # ------------------------------------------------------ interactive-data.json
    check('interactive-data.json carries a provenance note',
          isinstance(data.get('note'), str) and data['note'].strip(), 'absent or blank')

    inds = data['indicators']
    iids = [i.get('id') for i in inds]
    check('indicator ids are unique', len(iids) == len(set(iids)),
          'duplicates: %s' % sorted({i for i in iids if iids.count(i) > 1}))

    for ind in inds:
        iid = ind.get('id', '?')
        missing = sorted(CORE_KEYS - set(ind))
        check('%s carries every core key' % iid, not missing, 'missing %s' % missing)
        unknown = sorted(set(ind) - CORE_KEYS - OPTIONAL_KEYS)
        check('%s carries no unknown key' % iid, not unknown, 'unknown %s' % unknown)

        # The legend caption reads this. `null` is a deliberate third value for
        # an indicator with no normative direction (fertility, density, the
        # urban share, decadal growth), and the renderer captions those
        # differently. A string or a missing key does not throw; it captions a
        # map of infant mortality as though more were better.
        check('%s declares higherIsBetter as true, false or null' % iid,
              ind.get('higherIsBetter', 0) in (True, False, None),
              'is %r' % (ind.get('higherIsBetter'),))

        values = ind.get('values') or {}
        check('%s has values' % iid, bool(values), 'empty')

        # A state name the geojson does not know simply does not colour. There
        # is no error, no console warning, and the map looks finished.
        unmatched = sorted(set(values) - states)
        check('%s keys every value to a geojson state' % iid, not unmatched,
              'unmatched: %s' % unmatched)

        nonnum = sorted(k for k, v in values.items()
                        if not isinstance(v, (int, float)) or isinstance(v, bool)
                        or v != v)
        check('%s holds only finite numbers' % iid, not nonnum,
              'non-numeric: %s' % nonnum[:6])

        # A national figure outside the range of its own states means the two
        # were taken in different units or different vintages. Both render.
        nat = ind.get('national')
        nums = [v for v in values.values() if isinstance(v, (int, float))]
        if isinstance(nat, (int, float)) and nums:
            lo, hi = min(nums), max(nums)
            check('%s national figure sits inside its state range' % iid,
                  lo <= nat <= hi, '%s outside [%s, %s]' % (nat, lo, hi))

        check('%s sourceUrl is a URL' % iid,
              str(ind.get('sourceUrl', '')).startswith('http'),
              '%r' % (ind.get('sourceUrl'),))

        if 'retrieved' in ind:
            check('%s retrieved is an ISO date' % iid,
                  bool(re.fullmatch(r'\d{4}-\d{2}-\d{2}', str(ind['retrieved']))),
                  '%r' % (ind['retrieved'],))

        # mapId is the whole of the cross-link between the two views, in both
        # directions. A stale one renders a button leading to a 404.
        if 'mapId' in ind:
            check('%s mapId resolves in maps.json' % iid, ind['mapId'] in set(ids),
                  '%r' % (ind['mapId'],))
            check('%s mapId has a page' % iid,
                  os.path.exists(os.path.join(ROOT, 'm', '%s.html' % ind['mapId'])),
                  'm/%s.html absent' % ind['mapId'])

    # ------------------------------------------------------------------ sw.js
    # `cache.addAll` is all or nothing: one path that 404s rejects the whole
    # promise, the install fails, and the site silently ships with no offline
    # layer. Nothing on the page says so.
    sw = open(os.path.join(ROOT, 'sw.js'), encoding='utf-8').read()
    precache = re.search(r'const PRECACHE = \[(.*?)\];', sw, re.S)
    check('sw.js declares a PRECACHE list', precache is not None, 'not found')
    if precache:
        paths = [p for p in re.findall(r"'([^']+)'", precache.group(1))
                 if p.startswith('/')]
        check('sw.js precaches something', paths, 'empty')
        gone = [p for p in paths
                if not os.path.exists(os.path.join(ROOT, p.lstrip('/') or 'index.html'))]
        check('every precached path is on disk', not gone,
              'would fail the install: %s' % gone)
        # Both data files are precached, so a returning visitor keeps whichever
        # copy they already hold until the cache name changes.
        for f in ('/data/interactive-data.json', '/data/maps.json'):
            check('sw.js precaches %s' % f, f in paths,
                  'no longer precached, so this check needs revisiting')

    n_ind = len(inds)
    readme = open(os.path.join(ROOT, 'data/README.md'), encoding='utf-8').read()
    stale = sorted({int(n) for n in re.findall(r'\b(\d{1,3})\s+interactive indicators\b', readme)
                    if int(n) != n_ind})
    check('data/README.md states the indicator count as %d' % n_ind, not stale,
          'says %s' % stale)

    # ------------------------------------------------- the generated sheets
    #
    # Six of the sheets in maps/ are rendered by scripts/render/ from the
    # numbers in interactive-data.json rather than committed from elsewhere.
    # That is what makes them checkable at all: a generated sheet whose
    # indicator has been renamed, or whose catalogue entry has been removed,
    # is a PNG nobody can reproduce and nobody can find.
    sheets = load('scripts/render/sheets.json')
    map_by_id = {m['id']: m for m in maps}
    for sh in sheets:
        check('sheet %s names a live indicator' % sh['id'],
              sh['indicator'] in {i['id'] for i in inds},
              'no indicator %r' % sh['indicator'])
        check('sheet %s is in the catalogue' % sh['id'], sh['id'] in map_by_id,
              'missing from maps.json')
        entry = map_by_id.get(sh['id'], {})
        check('sheet %s and its catalogue entry name the same file' % sh['id'],
              entry.get('file') == sh['file'],
              'catalogue says %r, sheet says %r' % (entry.get('file'), sh['file']))
        check('sheet %s has been rendered' % sh['id'],
              os.path.exists(os.path.join(ROOT, 'maps', sh['section'], sh['file'])),
              'run scripts/render/render.py')
        ind = next((i for i in inds if i['id'] == sh['indicator']), {})
        check('indicator %s links back to sheet %s' % (sh['indicator'], sh['id']),
              ind.get('mapId') == sh['id'],
              'mapId is %r' % ind.get('mapId'))

    # ---------------------------------------------------------------- report
    if errors:
        print('FAIL: %d of %d checks' % (len(errors), checks))
        for e in errors:
            print('  - %s' % e)
        return 1
    print('PASS: %d checks' % checks)
    return 0


if __name__ == '__main__':
    sys.exit(main())
